checks:
  javascript: true
build:
    environment:
        variables:
            JWT_SECRET: "secretfortestonly"
            MONGO_HOST: "mongo"
            API_KEY: "secretfortestonly"
    services:
        mongo: 4
    nodes:
      analysis:
        coverage:
            tests:
                - command: npm test
                    coverage:
                      file: coverage/clover.xml
                      format: clover