build:
    environment:
        variables:
            JWT_SECRET: zY$meS}fgzih]HO|[atZ|+a`i`Yl894lHO9w6a
            MONGO_HOST: mongo
            API_KEY: h1pdghqwetrqwui3yhvpjfaeh9348u092jlkafjaskf90u98034hqina
    services:
        mongo: 4
    nodes:
        coverage:
        tests:
            override:
            - js-scrutinizer-run
            - command: npm test
                coverage:
                file: coverage/clover.xml
                format: clover