language: node_js

node_js:
    - "10"

env:
    JWT_SECRET: RY]ZVMYEa#c=RZ>9@
    MONGO_HOST: localhost
    API_KEY: sfh7834noiafjs8dy8

sudo: false

git:
    submodules: false

services: mongodb

before_script:
    - npm install

script:
    - npm run test

after_success:
    - npm run report-coveralls
    - npm run report-codecov